# generate_feeds.py

# Import the generate_feed function from the previous script
from feed_generator import generate_feed

# Define the feeds to generate
feeds = [
    {
        "title": "Sample RSS Feed",
        "subtitle": "This is a sample RSS feed generated by GitHub Action",
        "url": "https://www.example.com/",
        "author_name": "John Doe",
        "author_email": "john.doe@example.com",
        "language": "en",
        "item_title_selector": ".post-title",
        "item_url_selector": ".post-title a",
        "item_description_selector": ".post-content",
        "item_author_selector": ".post-author",
        "item_date_selector": ".post-date",
        "item_date_format": "dd MMM yyyy",
        "item_timezone": "UTC",
    },
    # Add more feeds here
]

# Generate each feed
for feed in feeds:
    generate_feed(**feed)
