name: Generate RSS Feeds

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "3 3 * * *" # Runs daily at 03:03 UTC

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    name: Generate RSS Feeds
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Generate RSS Feed for CHAOSS Blog
    - name: Generate RSS Feed for CHAOSS Blog
      uses: @gracefullight/rssify@v0.1.0
      with:
        TITLE: CHAOSS Blog RSS
        SUBTITLE: "Latest updates from CHAOSS Blog"
        URL: https://chaoss.community/blog/
        AUTHOR_NAME: "CHAOSS Community"
        AUTHOR_EMAIL: "info@chaoss.community"
        COPYRIGHT: "CHAOSS Community"
        LANGUAGE: "en"
        item-title-css: .title > a
        item-url-css: .title > a
       FILENAME: CHAOSS_Blog_RSS_feed # Output filename for the RSS feed

    # Generate RSS Feed for "Palavra do Dia"
    - name: Generate RSS Feed for Palavra do Dia
      uses: @gracefullight/rssify@v0.1.0
      with:
        TITLE: Palavra do Dia RSS
        SUBTITLE: "Palavra do Dia - Dicio"
        URL: https://www.dicio.com.br/palavra-do-dia/
        AUTHOR_NAME: "Dicio"
        AUTHOR_EMAIL: ""
        COPYRIGHT: "Dicio"
        LANGUAGE: "pt"
        item-title-css: .word-of-day .title
        item-url-css: .word-of-day .title a
        #ITEM_URL_CSS: true
        ITEM_DATE_CSS: .word-of-day .title
        #ITEM_AUTHOR_CSS: false
        ITEM_DESCRIPTION_CSS: .word-of-day--text-wrap .word-of-day--description
        ITEM_IMAGE_CSS: .word-of-day picture img
        ITEM_DATE_FORMAT: "dd/MM/yyyy" # Date format for items
        ITEM_TIMEZONE: "America/Sao_Paulo" # Timezone for GMT-3
        FILENAME: Palavra_do_Dia_RSS_feed # Output filename for the RSS feed
