name: Generate RSS Feeds

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "3 3 * * *" # Runs daily at 03:03 UTC

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    name: Generate RSS Feeds
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to latest version
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedgen beautifulsoup4 feedparser gitpython

      - name: Generate RSS and JSON Feeds
        run: |
          python generate_feeds.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify and Push Changes
        if: success() # Only run if previous step succeeds
        run: |
          git pull origin main --rebase # Rebase to avoid merge commits
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
