name: Generate RSS Feeds

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "3 3 * * *" # Runs daily at 03:03 UTC

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    name: Generate RSS Feeds
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests feedgen beautifulsoup4 lxml pytz feedparser

      - name: Generate RSS and JSON Feeds
        run: |
          python generate_feeds.py
          
          # Configure git
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          # Pull the latest changes to avoid conflicts
          git pull origin main
          
          # Add changes to git
          git add feeds/**/*.xml feeds/**/*.json
          
          # Commit and push if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update RSS and JSON Feeds"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
