name: Generate RSS Feeds

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "3 3 * * *" # Runs daily at 03:03 UTC

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    name: Generate RSS Feeds
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests feedgen beautifulsoup4 lxml pytz

    - name: Generate RSS and JSON Feeds
      env:
        # Define feed prefixes
        FEED_PREFIXES: "FEED1,FEED2"
        # Feed 1
        FEED1_TITLE: "Palavra do Dia RSS"
        FEED1_SUBTITLE: "Daily words from Dicio"
        FEED1_URL: "https://www.dicio.com.br/palavra-do-dia/"
        FEED1_AUTHOR_NAME: "Dicio"
        FEED1_AUTHOR_EMAIL: "contact@dicio.com.br"
        FEED1_COPYRIGHT: "Dicio"
        FEED1_LANGUAGE: "pt"
        FEED1_ITEM_TITLE_CSS: ".word-of-day .title"
        FEED1_ITEM_URL_CSS: ".word-of-day--subtitle a"
        FEED1_ITEM_AUTHOR_CSS: ""
        FEED1_ITEM_DESCRIPTION_CSS: ".word-of-day--text-wrap .word-of-day--description, .word-of-day--extra"
        FEED1_ITEM_DATE_CSS: ".word-of-day .title"
        FEED1_ITEM_DATE_FORMAT: "%d/%m/%Y"
        FEED1_ITEM_TIMEZONE: "America/Sao_Paulo"
        FEED1_OUTPUT_PATH: "feeds/palavra_do_dia"
        FEED1_FORMATS: "xml,json"
        # Feed 2 Example
        FEED2_TITLE: "Example Feed RSS"
        FEED2_SUBTITLE: "Example subtitle"
        FEED2_URL: "https://www.example.com/feed/"
        FEED2_AUTHOR_NAME: "Example Author"
        FEED2_AUTHOR_EMAIL: "author@example.com"
        FEED2_COPYRIGHT: "Example"
        FEED2_LANGUAGE: "en"
        FEED2_ITEM_TITLE_CSS: ".example-title"
        FEED2_ITEM_URL_CSS: ".example-url a"
        FEED2_ITEM_AUTHOR_CSS: ".example-author"
        FEED2_ITEM_DESCRIPTION_CSS: ".example-description"
        FEED2_ITEM_DATE_CSS: ".example-date"
        FEED2_ITEM_DATE_FORMAT: "%Y-%m-%d"
        FEED2_ITEM_TIMEZONE: "UTC"
        FEED2_OUTPUT_PATH: "feeds/example_feed"
        FEED2_FORMATS: "xml,json"
      run: python generate_feeds.py

    - name: Commit and Push RSS Feeds
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add feeds/**/*.xml feeds/**/*.json
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update RSS and JSON Feeds"
          git push
        else
          echo "No changes to commit"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
