name: Generate RSS Feeds

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "3 3 * * *" # Runs daily at 03:03 UTC

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    name: Generate RSS Feeds
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests feedgen beautifulsoup4 lxml pytz

      - name: Run Feed Generation Script
        run: python generate_feeds.py

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Add Feeds
        run: git add feeds/**/*.xml feeds/**/*.json

      - name: Commit Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update RSS and JSON Feeds"
            git push
          else
            echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
